; Listing generated by Microsoft (R) Optimizing Compiler Version 14.00.50727.762 

	TITLE	i:\os\10\a\krnl\krnl\cpu.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	?i86_cpu_initialize@@YAHXZ			; i86_cpu_initialize
EXTRN	?i86_idt_initialize@@YAHG@Z:PROC		; i86_idt_initialize
EXTRN	?i86_gdt_initialize@@YAHXZ:PROC			; i86_gdt_initialize
EXTRN	?k_reenter@@3HA:DWORD				; k_reenter
; Function compile flags: /Ogtpy
; File i:\os\10\a\krnl\krnl\cpu.cpp
;	COMDAT ?i86_cpu_initialize@@YAHXZ
_TEXT	SEGMENT
?i86_cpu_initialize@@YAHXZ PROC				; i86_cpu_initialize, COMDAT

; 7    : 	k_reenter = 0;

	mov	DWORD PTR ?k_reenter@@3HA, 0		; k_reenter

; 8    : 	i86_gdt_initialize();

	call	?i86_gdt_initialize@@YAHXZ		; i86_gdt_initialize

; 9    : 	i86_idt_initialize( 0x8 );

	push	8
	call	?i86_idt_initialize@@YAHG@Z		; i86_idt_initialize
	add	esp, 4

; 10   : 	return 0;

	xor	eax, eax

; 11   : }

	ret	0
?i86_cpu_initialize@@YAHXZ ENDP				; i86_cpu_initialize
_TEXT	ENDS
END
