; Listing generated by Microsoft (R) Optimizing Compiler Version 14.00.50727.762 

	TITLE	i:\os\10\a\krnl\krnl\entry.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	?kernelSize@@3GA				; kernelSize
_BSS	SEGMENT
?kernelSize@@3GA DW 01H DUP (?)				; kernelSize
_BSS	ENDS
PUBLIC	??_C@_0BL@HFEDFKHD@Kernel?5size?3?5?$CFd?$CIsectors?$CJ?4?6?$AA@ ; `string'
PUBLIC	?kernel_entry@@YAXPAU_tag_boot_info@@@Z		; kernel_entry
EXTRN	?kernel_main@@YAHPAU_tag_boot_info@@@Z:PROC	; kernel_main
EXTRN	?DbgPrintf@@YAHPBDZZ:PROC			; DbgPrintf
EXTRN	?DbgCls@@YAXE@Z:PROC				; DbgCls
;	COMDAT ??_C@_0BL@HFEDFKHD@Kernel?5size?3?5?$CFd?$CIsectors?$CJ?4?6?$AA@
; File i:\os\10\a\krnl\krnl\entry.cpp
CONST	SEGMENT
??_C@_0BL@HFEDFKHD@Kernel?5size?3?5?$CFd?$CIsectors?$CJ?4?6?$AA@ DB 'Kern'
	DB	'el size: %d(sectors).', 0aH, 00H		; `string'
; Function compile flags: /Ogtpy
CONST	ENDS
;	COMDAT ?kernel_entry@@YAXPAU_tag_boot_info@@@Z
_TEXT	SEGMENT
_bootinfo$ = 8						; size = 4
?kernel_entry@@YAXPAU_tag_boot_info@@@Z PROC		; kernel_entry, COMDAT

; 12   : 	_asm mov word ptr[kernelSize],dx

	mov	WORD PTR ?kernelSize@@3GA, dx		; kernelSize

; 13   : 
; 14   : 	_asm{
; 15   : 		cli

	cli

; 16   : 		mov ax,10h

	mov	ax, 16					; 00000010H

; 17   : 		mov ds,ax

	mov	ds, ax

; 18   : 		mov es,ax

	mov	es, ax

; 19   : 		mov fs,ax

	mov	fs, ax

; 20   : 		mov gs,ax

	mov	gs, ax

; 21   : 	}
; 22   : 
; 23   : 	DbgCls(0x7);

	push	7
	call	?DbgCls@@YAXE@Z				; DbgCls

; 24   : 
; 25   : 	DbgPrintf("Kernel size: %d(sectors).\n",kernelSize);

	movzx	eax, WORD PTR ?kernelSize@@3GA		; kernelSize
	push	eax
	push	OFFSET ??_C@_0BL@HFEDFKHD@Kernel?5size?3?5?$CFd?$CIsectors?$CJ?4?6?$AA@
	call	?DbgPrintf@@YAHPBDZZ			; DbgPrintf

; 26   : 
; 27   : 	kernel_main(bootinfo);

	mov	ecx, DWORD PTR _bootinfo$[esp+8]
	push	ecx
	call	?kernel_main@@YAHPAU_tag_boot_info@@@Z	; kernel_main
	add	esp, 16					; 00000010H
	npad	2
$hlt$2915:

; 28   : 
; 29   : hlt:
; 30   : 	goto hlt;

	jmp	SHORT $hlt$2915
?kernel_entry@@YAXPAU_tag_boot_info@@@Z ENDP		; kernel_entry
_TEXT	ENDS
END
