; Listing generated by Microsoft (R) Optimizing Compiler Version 14.00.50727.762 

	TITLE	i:\os\10\a\krnl\krnl\exec.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	?exec@@YAHPAD@Z					; exec
EXTRN	?send_recv@@YAHHHPAU_tagMESSAGE@@@Z:PROC	; send_recv
EXTRN	?strlen@@YAIPBD@Z:PROC				; strlen
; Function compile flags: /Ogtpy
; File i:\os\10\a\krnl\krnl\exec.cpp
;	COMDAT ?exec@@YAHPAD@Z
_TEXT	SEGMENT
_msg$ = -48						; size = 48
_pathname$ = 8						; size = 4
?exec@@YAHPAD@Z PROC					; exec, COMDAT

; 6    : {

	sub	esp, 48					; 00000030H
	push	esi

; 7    : 	MESSAGE msg;
; 8    : 	msg.NAME_LEN = strlen(pathname);

	mov	esi, DWORD PTR _pathname$[esp+48]
	push	esi
	call	?strlen@@YAIPBD@Z			; strlen
	mov	DWORD PTR _msg$[esp+68], eax

; 9    : 	msg.PATHNAME = pathname;
; 10   : 	msg.type = EXCUTE;
; 11   : 
; 12   : 	send_recv(BOTH,TASK_SYS,&msg);

	lea	eax, DWORD PTR _msg$[esp+56]
	push	eax
	push	1
	push	3
	mov	DWORD PTR _msg$[esp+108], esi
	mov	DWORD PTR _msg$[esp+72], 1014		; 000003f6H
	call	?send_recv@@YAHHHPAU_tagMESSAGE@@@Z	; send_recv

; 13   : 	return msg.RETVAL;

	mov	eax, DWORD PTR _msg$[esp+76]
	add	esp, 16					; 00000010H
	pop	esi

; 14   : }

	add	esp, 48					; 00000030H
	ret	0
?exec@@YAHPAD@Z ENDP					; exec
_TEXT	ENDS
END
