; Listing generated by Microsoft (R) Optimizing Compiler Version 14.00.50727.762 

	TITLE	i:\os\10\a\krnl\krnl\exit.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	?exit@@YAXH@Z					; exit
EXTRN	?send_recv@@YAHHHPAU_tagMESSAGE@@@Z:PROC	; send_recv
; Function compile flags: /Ogtpy
; File i:\os\10\a\krnl\krnl\exit.cpp
;	COMDAT ?exit@@YAXH@Z
_TEXT	SEGMENT
_msg$ = -48						; size = 48
_code$ = 8						; size = 4
?exit@@YAXH@Z PROC					; exit, COMDAT

; 4    : {

	sub	esp, 48					; 00000030H

; 5    : 	MESSAGE msg;
; 6    : 
; 7    : 	msg.type = EXIT;
; 8    : 	msg.STATUS = code;

	mov	eax, DWORD PTR _code$[esp+44]

; 9    : 	send_recv(BOTH,TASK_SYS,&msg);

	lea	ecx, DWORD PTR _msg$[esp+48]
	push	ecx
	push	1
	push	3
	mov	DWORD PTR _msg$[esp+64], 1013		; 000003f5H
	mov	DWORD PTR _msg$[esp+68], eax
	call	?send_recv@@YAHHHPAU_tagMESSAGE@@@Z	; send_recv

; 10   : }

	add	esp, 60					; 0000003cH
	ret	0
?exit@@YAXH@Z ENDP					; exit
_TEXT	ENDS
END
