; Listing generated by Microsoft (R) Optimizing Compiler Version 14.00.50727.762 

	TITLE	i:\os\09\i\krnl\krnl\fork.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	?fork@@YAHXZ					; fork
EXTRN	?send_recv@@YAHHHPAU_tagMESSAGE@@@Z:PROC	; send_recv
; Function compile flags: /Ogtpy
; File i:\os\09\i\krnl\krnl\fork.cpp
;	COMDAT ?fork@@YAHXZ
_TEXT	SEGMENT
_msg$ = -48						; size = 48
?fork@@YAHXZ PROC					; fork, COMDAT

; 4    : {

	sub	esp, 48					; 00000030H

; 5    : 	MESSAGE msg;
; 6    : 
; 7    : 	msg.type = FORK;
; 8    : 	send_recv(BOTH,TASK_SYS,&msg);

	lea	eax, DWORD PTR _msg$[esp+48]
	push	eax
	push	1
	push	3
	mov	DWORD PTR _msg$[esp+64], 1012		; 000003f4H
	call	?send_recv@@YAHHHPAU_tagMESSAGE@@@Z	; send_recv

; 9    : 
; 10   : 	return msg.PID;

	mov	eax, DWORD PTR _msg$[esp+72]

; 11   : }

	add	esp, 60					; 0000003cH
	ret	0
?fork@@YAHXZ ENDP					; fork
_TEXT	ENDS
END
