; Listing generated by Microsoft (R) Optimizing Compiler Version 14.00.50727.762 

	TITLE	i:\os\10\a\krnl\krnl\gate.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	?i86_set_gate@@YAXPAUgate@@GIEE@Z		; i86_set_gate
; Function compile flags: /Ogtpy
; File i:\os\10\a\krnl\krnl\gate.cpp
;	COMDAT ?i86_set_gate@@YAXPAUgate@@GIEE@Z
_TEXT	SEGMENT
_gt$ = 8						; size = 4
_sel$ = 12						; size = 2
_offset$ = 16						; size = 4
_dcount$ = 20						; size = 1
_attr$ = 24						; size = 1
?i86_set_gate@@YAXPAUgate@@GIEE@Z PROC			; i86_set_gate, COMDAT

; 5    : 	gt->offsetLo = offset & 0xffff;

	mov	ecx, DWORD PTR _gt$[esp-4]

; 6    : 	gt->sel = sel;

	mov	dx, WORD PTR _sel$[esp-4]
	mov	eax, DWORD PTR _offset$[esp-4]
	mov	WORD PTR [ecx+2], dx

; 7    : 	gt->attr = (dcount & 0x1f) | ((attr << 8) & 0xff00);

	mov	dl, BYTE PTR _dcount$[esp-4]
	and	dl, 31					; 0000001fH
	movzx	dx, dl
	mov	dh, BYTE PTR _attr$[esp-4]
	mov	WORD PTR [ecx], ax

; 8    : 	gt->offsetHi = (offset >> 16) & 0xffff;

	shr	eax, 16					; 00000010H
	mov	WORD PTR [ecx+6], ax
	mov	WORD PTR [ecx+4], dx

; 9    : }

	ret	0
?i86_set_gate@@YAXPAUgate@@GIEE@Z ENDP			; i86_set_gate
_TEXT	ENDS
END
