; Listing generated by Microsoft (R) Optimizing Compiler Version 14.00.50727.762 

	TITLE	i:\os\10\a\krnl\krnl\hal.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	?setvect@@YAXHP6AXXZ@Z				; setvect
EXTRN	?init_idt_desc@@YAXIP6AXXZEEG@Z:PROC		; init_idt_desc
; Function compile flags: /Ogtpy
; File i:\os\10\a\krnl\krnl\hal.cpp
;	COMDAT ?setvect@@YAXHP6AXXZ@Z
_TEXT	SEGMENT
_intno$ = 8						; size = 4
_vect$ = 12						; size = 4
?setvect@@YAXHP6AXXZ@Z PROC				; setvect, COMDAT

; 6    : 	init_idt_desc(intno,vect,DA_386IGATE,PRIVILEGE_KRNL,0x8);

	mov	eax, DWORD PTR _vect$[esp-4]
	mov	ecx, DWORD PTR _intno$[esp-4]
	push	8
	push	0
	push	142					; 0000008eH
	push	eax
	push	ecx
	call	?init_idt_desc@@YAXIP6AXXZEEG@Z		; init_idt_desc
	add	esp, 20					; 00000014H

; 7    : }

	ret	0
?setvect@@YAXHP6AXXZ@Z ENDP				; setvect
_TEXT	ENDS
PUBLIC	?i86_hal_initialize@@YAHXZ			; i86_hal_initialize
EXTRN	?enable_interrupt@@YAXXZ:PROC			; enable_interrupt
EXTRN	?i86_pic_initialize@@YAXXZ:PROC			; i86_pic_initialize
EXTRN	?i86_cpu_initialize@@YAHXZ:PROC			; i86_cpu_initialize
EXTRN	?disable_interrupt@@YAXXZ:PROC			; disable_interrupt
; Function compile flags: /Ogtpy
;	COMDAT ?i86_hal_initialize@@YAHXZ
_TEXT	SEGMENT
?i86_hal_initialize@@YAHXZ PROC				; i86_hal_initialize, COMDAT

; 11   : 	disable_interrupt();

	call	?disable_interrupt@@YAXXZ		; disable_interrupt

; 12   : 
; 13   : 	i86_cpu_initialize();

	call	?i86_cpu_initialize@@YAHXZ		; i86_cpu_initialize

; 14   : 	i86_pic_initialize();

	call	?i86_pic_initialize@@YAXXZ		; i86_pic_initialize

; 15   : 
; 16   : 	enable_interrupt();

	call	?enable_interrupt@@YAXXZ		; enable_interrupt

; 17   : 	return 0;

	xor	eax, eax

; 18   : }

	ret	0
?i86_hal_initialize@@YAHXZ ENDP				; i86_hal_initialize
_TEXT	ENDS
END
