; Listing generated by Microsoft (R) Optimizing Compiler Version 14.00.50727.762 

	TITLE	i:\os\09\a\krnl\krnl\hd.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	?task_hd@@YAXXZ					; task_hd
EXTRN	?send_recv@@YAHHHPAU_tagMESSAGE@@@Z:PROC	; send_recv
; Function compile flags: /Ogtpy
; File i:\os\09\a\krnl\krnl\hd.cpp
;	COMDAT ?task_hd@@YAXXZ
_TEXT	SEGMENT
_msg$ = -52						; size = 52
?task_hd@@YAXXZ PROC					; task_hd, COMDAT

; 5    : {

	sub	esp, 52					; 00000034H
$LL6@task_hd:

; 6    : 	MESSAGE	msg;
; 7    : 
; 8    : 	//init_hd();
; 9    : 
; 10   : 	while(1){
; 11   : 		send_recv(RECEIVE,ANY,&msg);

	lea	eax, DWORD PTR _msg$[esp+52]
	push	eax
	push	14					; 0000000eH
	push	2
	call	?send_recv@@YAHHHPAU_tagMESSAGE@@@Z	; send_recv

; 12   : 
; 13   : 		int src = msg.source;
; 14   : 
; 15   : 		switch(msg.type){
; 16   : 		case DEV_OPEN:
; 17   : 			{
; 18   : 				//hd_identify(0);
; 19   : 			}
; 20   : 			break;
; 21   : 		default:
; 22   : 			break;
; 23   : 		}
; 24   : 		send_recv(SEND,src,&msg);

	mov	edx, DWORD PTR _msg$[esp+64]
	lea	ecx, DWORD PTR _msg$[esp+64]
	push	ecx
	push	edx
	push	1
	call	?send_recv@@YAHHHPAU_tagMESSAGE@@@Z	; send_recv
	add	esp, 24					; 00000018H

; 25   : 	}

	jmp	SHORT $LL6@task_hd
?task_hd@@YAXXZ ENDP					; task_hd
_TEXT	ENDS
END
