; Listing generated by Microsoft (R) Optimizing Compiler Version 14.00.50727.762 

	TITLE	i:\os\10\a\krnl\krnl\idt.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	?_idtr@@3Uidtr@@A				; _idtr
PUBLIC	?idt@@3PAUgate@@A				; idt
PUBLIC	?k_reenter@@3HA					; k_reenter
_BSS	SEGMENT
?_idtr@@3Uidtr@@A DF 01H DUP (?)			; _idtr
	ALIGN	8

?idt@@3PAUgate@@A DQ 0100H DUP (?)			; idt
?k_reenter@@3HA DD 01H DUP (?)				; k_reenter
_BSS	ENDS
PUBLIC	??_C@_0L@ILIMGEIG@interrupt?6?$AA@		; `string'
PUBLIC	?i86_default_handler@@YAXXZ			; i86_default_handler
EXTRN	?DbgPrintf@@YAHPBDZZ:PROC			; DbgPrintf
EXTRN	?disable_interrupt@@YAXXZ:PROC			; disable_interrupt
;	COMDAT ??_C@_0L@ILIMGEIG@interrupt?6?$AA@
; File i:\os\10\a\krnl\krnl\idt.cpp
CONST	SEGMENT
??_C@_0L@ILIMGEIG@interrupt?6?$AA@ DB 'interrupt', 0aH, 00H ; `string'
; Function compile flags: /Ogtpy
CONST	ENDS
;	COMDAT ?i86_default_handler@@YAXXZ
_TEXT	SEGMENT
?i86_default_handler@@YAXXZ PROC			; i86_default_handler, COMDAT

; 12   : 	disable_interrupt();

	call	?disable_interrupt@@YAXXZ		; disable_interrupt

; 13   : 	DbgPrintf("interrupt\n");

	push	OFFSET ??_C@_0L@ILIMGEIG@interrupt?6?$AA@
	call	?DbgPrintf@@YAHPBDZZ			; DbgPrintf
	add	esp, 4
$LL2@i86_defaul:

; 14   : 	for(;;);					//	halt

	jmp	SHORT $LL2@i86_defaul
?i86_default_handler@@YAXXZ ENDP			; i86_default_handler
_TEXT	ENDS
PUBLIC	?init_idt_desc@@YAXIP6AXXZEEG@Z			; init_idt_desc
EXTRN	?i86_set_gate@@YAXPAUgate@@GIEE@Z:PROC		; i86_set_gate
; Function compile flags: /Ogtpy
;	COMDAT ?init_idt_desc@@YAXIP6AXXZEEG@Z
_TEXT	SEGMENT
_i$ = 8							; size = 4
_handler$ = 12						; size = 4
_type$ = 16						; size = 1
_privilege$ = 20					; size = 1
_codeSel$ = 24						; size = 2
?init_idt_desc@@YAXIP6AXXZEEG@Z PROC			; init_idt_desc, COMDAT

; 19   : 	if(i >= IDT_SIZE){

	mov	eax, DWORD PTR _i$[esp-4]
	cmp	eax, 256				; 00000100H
	jae	SHORT $LN2@init_idt_d

; 20   : 		return ;
; 21   : 	}
; 22   : 	i86_set_gate(&idt[i],codeSel,(uint32_t)handler,0,type | (privilege << 5));

	movzx	ecx, BYTE PTR _privilege$[esp-4]
	mov	edx, DWORD PTR _handler$[esp-4]
	shl	cl, 5
	or	cl, BYTE PTR _type$[esp-4]
	push	ecx
	mov	ecx, DWORD PTR _codeSel$[esp]
	push	0
	push	edx
	push	ecx
	lea	edx, DWORD PTR ?idt@@3PAUgate@@A[eax*8]
	push	edx
	call	?i86_set_gate@@YAXPAUgate@@GIEE@Z	; i86_set_gate
	add	esp, 20					; 00000014H
$LN2@init_idt_d:

; 23   : }

	ret	0
?init_idt_desc@@YAXIP6AXXZEEG@Z ENDP			; init_idt_desc
_TEXT	ENDS
PUBLIC	?idt_install@@YAXXZ				; idt_install
; Function compile flags: /Ogtpy
;	COMDAT ?idt_install@@YAXXZ
_TEXT	SEGMENT
?idt_install@@YAXXZ PROC				; idt_install, COMDAT

; 41   : 	_asm lidt [_idtr]

	lidt	FWORD PTR ?_idtr@@3Uidtr@@A		; _idtr

; 42   : }

	ret	0
?idt_install@@YAXXZ ENDP				; idt_install
_TEXT	ENDS
PUBLIC	?i86_idt_initialize@@YAHG@Z			; i86_idt_initialize
EXTRN	?memset@@YAPAXPAXDI@Z:PROC			; memset
; Function compile flags: /Ogtpy
;	COMDAT ?i86_idt_initialize@@YAHG@Z
_TEXT	SEGMENT
_codeSel$ = 8						; size = 2
?i86_idt_initialize@@YAHG@Z PROC			; i86_idt_initialize, COMDAT

; 26   : {

	push	ebx
	push	esi
	push	edi

; 27   : 	_idtr.limit = sizeof(GATE) * IDT_SIZE - 1;
; 28   : 	_idtr.base	= (uint32_t) &idt[0];
; 29   : 
; 30   : 	memset((void*)&idt[0],0,sizeof(GATE) * IDT_SIZE);

	push	2048					; 00000800H
	mov	esi, OFFSET ?idt@@3PAUgate@@A		; idt
	push	0
	push	esi
	mov	WORD PTR ?_idtr@@3Uidtr@@A, 2047	; 000007ffH
	mov	DWORD PTR ?_idtr@@3Uidtr@@A+2, esi
	call	?memset@@YAPAXPAXDI@Z			; memset
	mov	ebx, DWORD PTR _codeSel$[esp+20]
	add	esp, 12					; 0000000cH

; 31   : 
; 32   : 	for(int i = 0;i < IDT_SIZE;i++){

	xor	edi, edi
	npad	3
$LL3@i86_idt_in:

; 33   : 		init_idt_desc(i,i86_default_handler,DA_386IGATE,PRIVILEGE_KRNL,codeSel);

	cmp	edi, 256				; 00000100H
	jae	SHORT $LN2@i86_idt_in
	push	142					; 0000008eH
	push	0
	push	OFFSET ?i86_default_handler@@YAXXZ	; i86_default_handler
	push	ebx
	push	esi
	call	?i86_set_gate@@YAXPAUgate@@GIEE@Z	; i86_set_gate
	add	esp, 20					; 00000014H
$LN2@i86_idt_in:
	add	esi, 8
	add	edi, 1
	cmp	esi, OFFSET ?idt@@3PAUgate@@A+2048
	jl	SHORT $LL3@i86_idt_in

; 34   : 	}
; 35   : 
; 36   : 	idt_install();

	lidt	FWORD PTR ?_idtr@@3Uidtr@@A		; _idtr
	pop	edi
	pop	esi
	pop	ebx

; 37   : }

	ret	0
?i86_idt_initialize@@YAHG@Z ENDP			; i86_idt_initialize
_TEXT	ENDS
END
