; Listing generated by Microsoft (R) Optimizing Compiler Version 14.00.50727.762 

	TITLE	i:\os\10\a\krnl\krnl\misc.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	?min@@YAHHH@Z					; min
; Function compile flags: /Ogtpy
; File i:\os\10\a\krnl\krnl\misc.cpp
;	COMDAT ?min@@YAHHH@Z
_TEXT	SEGMENT
_a$ = 8							; size = 4
_b$ = 12						; size = 4
?min@@YAHHH@Z PROC					; min, COMDAT

; 5    : 	return a < b ? a : b;

	mov	eax, DWORD PTR _a$[esp-4]
	mov	ecx, DWORD PTR _b$[esp-4]
	cmp	eax, ecx
	jl	SHORT $LN4@min
	mov	eax, ecx
$LN4@min:

; 6    : }

	ret	0
?min@@YAHHH@Z ENDP					; min
_TEXT	ENDS
PUBLIC	?max@@YAHHH@Z					; max
; Function compile flags: /Ogtpy
;	COMDAT ?max@@YAHHH@Z
_TEXT	SEGMENT
_a$ = 8							; size = 4
_b$ = 12						; size = 4
?max@@YAHHH@Z PROC					; max, COMDAT

; 10   : 	return a > b ? a : b;

	mov	eax, DWORD PTR _a$[esp-4]
	mov	ecx, DWORD PTR _b$[esp-4]
	cmp	eax, ecx
	jg	SHORT $LN4@max
	mov	eax, ecx
$LN4@max:

; 11   : }

	ret	0
?max@@YAHHH@Z ENDP					; max
_TEXT	ENDS
END
