; Listing generated by Microsoft (R) Optimizing Compiler Version 14.00.50727.762 

	TITLE	i:\os\10\a\krnl\krnl\open.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	?open@@YAHPAD@Z					; open
EXTRN	?send_recv@@YAHHHPAU_tagMESSAGE@@@Z:PROC	; send_recv
EXTRN	?strlen@@YAIPBD@Z:PROC				; strlen
; Function compile flags: /Ogtpy
; File i:\os\10\a\krnl\krnl\open.cpp
;	COMDAT ?open@@YAHPAD@Z
_TEXT	SEGMENT
_msg$ = -48						; size = 48
_filename$ = 8						; size = 4
?open@@YAHPAD@Z PROC					; open, COMDAT

; 7    : {

	sub	esp, 48					; 00000030H

; 8    : 	MESSAGE	msg;
; 9    : 
; 10   : 	msg.PATHNAME = filename;

	mov	eax, DWORD PTR _filename$[esp+44]

; 11   : 	msg.NAME_LEN = strlen(filename);

	push	eax
	mov	DWORD PTR _msg$[esp+92], eax
	call	?strlen@@YAIPBD@Z			; strlen
	mov	DWORD PTR _msg$[esp+64], eax

; 12   : 	msg.type = OPEN;
; 13   : 
; 14   : 	send_recv(BOTH,TASK_FS,&msg);

	lea	eax, DWORD PTR _msg$[esp+52]
	push	eax
	push	3
	push	3
	mov	DWORD PTR _msg$[esp+68], 1006		; 000003eeH
	call	?send_recv@@YAHHHPAU_tagMESSAGE@@@Z	; send_recv

; 15   : 	return msg.FD;

	mov	eax, DWORD PTR _msg$[esp+72]

; 16   : }

	add	esp, 64					; 00000040H
	ret	0
?open@@YAHPAD@Z ENDP					; open
_TEXT	ENDS
END
