; Listing generated by Microsoft (R) Optimizing Compiler Version 14.00.50727.762 

	TITLE	i:\os\10\a\krnl\krnl\pic.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	?init_8259a@@YAXXZ				; init_8259a
EXTRN	?out_byte@@YAXGE@Z:PROC				; out_byte
; Function compile flags: /Ogtpy
; File i:\os\10\a\krnl\krnl\pic.cpp
;	COMDAT ?init_8259a@@YAXXZ
_TEXT	SEGMENT
?init_8259a@@YAXXZ PROC					; init_8259a, COMDAT

; 6    : 	//	master 8259,ICW1
; 7    : 	out_byte(INT_M_CTL,0x11);

	push	17					; 00000011H
	push	32					; 00000020H
	call	?out_byte@@YAXGE@Z			; out_byte

; 8    : 	//	slave 8259,ICW1
; 9    : 	out_byte(INT_S_CTL,0x11);

	push	17					; 00000011H
	push	160					; 000000a0H
	call	?out_byte@@YAXGE@Z			; out_byte

; 10   : 
; 11   : 	//	master 8259,ICW2, set mater 8259 interrupt entry to 0x20
; 12   : 	out_byte(INT_M_CTLMASK,INT_VECTOR_IRQ0);

	push	32					; 00000020H
	push	33					; 00000021H
	call	?out_byte@@YAXGE@Z			; out_byte

; 13   : 	//	slave 8259,ICW2, set mater 8259 interrupt entry to 0x28
; 14   : 	out_byte(INT_S_CTLMASK,INT_VECTOR_IRQ8);

	push	40					; 00000028H
	push	161					; 000000a1H
	call	?out_byte@@YAXGE@Z			; out_byte

; 15   : 
; 16   : 	//	master 8259,ICW3, IR2 refer to slave 8259
; 17   : 	out_byte(INT_M_CTLMASK,0x4);

	push	4
	push	33					; 00000021H
	call	?out_byte@@YAXGE@Z			; out_byte

; 18   : 	//	slave 8259,ICW3, refer to master 8259 IR2
; 19   : 	out_byte(INT_S_CTLMASK,0x2);

	push	2
	push	161					; 000000a1H
	call	?out_byte@@YAXGE@Z			; out_byte

; 20   : 
; 21   : 	//	master ICW4
; 22   : 	out_byte(INT_M_CTLMASK,0x1);

	push	1
	push	33					; 00000021H
	call	?out_byte@@YAXGE@Z			; out_byte

; 23   : 	//	slave ICW4
; 24   : 	out_byte(INT_S_CTLMASK,0x1);

	push	1
	push	161					; 000000a1H
	call	?out_byte@@YAXGE@Z			; out_byte
	add	esp, 64					; 00000040H

; 25   : 
; 26   : 	//	master OCW1
; 27   : 	out_byte(INT_M_CTLMASK,0xff);

	push	255					; 000000ffH
	push	33					; 00000021H
	call	?out_byte@@YAXGE@Z			; out_byte

; 28   : 	//	slave OCW1
; 29   : 	out_byte(INT_S_CTLMASK,0xff);

	push	255					; 000000ffH
	push	161					; 000000a1H
	call	?out_byte@@YAXGE@Z			; out_byte
	add	esp, 16					; 00000010H

; 30   : }

	ret	0
?init_8259a@@YAXXZ ENDP					; init_8259a
_TEXT	ENDS
PUBLIC	?i86_pic_initialize@@YAXXZ			; i86_pic_initialize
; Function compile flags: /Ogtpy
;	COMDAT ?i86_pic_initialize@@YAXXZ
_TEXT	SEGMENT
?i86_pic_initialize@@YAXXZ PROC				; i86_pic_initialize, COMDAT

; 34   : 	init_8259a();

	jmp	?init_8259a@@YAXXZ			; init_8259a
?i86_pic_initialize@@YAXXZ ENDP				; i86_pic_initialize
_TEXT	ENDS
END
