; Listing generated by Microsoft (R) Optimizing Compiler Version 14.00.50727.762 

	TITLE	i:\os\10\a\krnl\krnl\printf.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	?printf@@YAHPBDZZ				; printf
EXTRN	?printx@@YAHPADH@Z:PROC				; printx
EXTRN	?vsprintf@@YAHPADPBDPAE@Z:PROC			; vsprintf
; Function compile flags: /Ogtpy
; File i:\os\10\a\krnl\krnl\printf.cpp
;	COMDAT ?printf@@YAHPBDZZ
_TEXT	SEGMENT
_buf$ = -256						; size = 256
_fmt$ = 8						; size = 4
?printf@@YAHPBDZZ PROC					; printf, COMDAT

; 6    : 	int i;
; 7    : 	char buf[256];
; 8    : 
; 9    : 	va_list arg = (va_list)((char*)(&fmt) + 4);
; 10   : 	i = vsprintf(buf,fmt,arg);

	mov	ecx, DWORD PTR _fmt$[esp-4]
	sub	esp, 256				; 00000100H
	push	esi
	lea	eax, DWORD PTR _fmt$[esp+260]
	push	eax
	push	ecx
	lea	edx, DWORD PTR _buf$[esp+268]
	push	edx
	call	?vsprintf@@YAHPADPBDPAE@Z		; vsprintf
	mov	esi, eax

; 11   : 	printx(buf,i);

	lea	eax, DWORD PTR _buf$[esp+272]
	push	esi
	push	eax
	call	?printx@@YAHPADH@Z			; printx
	add	esp, 20					; 00000014H

; 12   : 
; 13   : 	return i;

	mov	eax, esi
	pop	esi

; 14   : }

	add	esp, 256				; 00000100H
	ret	0
?printf@@YAHPBDZZ ENDP					; printf
_TEXT	ENDS
END
