; Listing generated by Microsoft (R) Optimizing Compiler Version 14.00.50727.762 

	TITLE	i:\os\10\a\krnl\krnl\printx.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	?printx@@YAHPADH@Z				; printx
; Function compile flags: /Ogtpy
; File i:\os\10\a\krnl\krnl\printx.cpp
;	COMDAT ?printx@@YAHPADH@Z
_TEXT	SEGMENT
_buf$ = 8						; size = 4
_len$ = 12						; size = 4
?printx@@YAHPADH@Z PROC					; printx, COMDAT

; 5    : 	_asm{
; 6    : 		mov eax,SYS_PRINT

	mov	eax, 2

; 7    : 		mov ecx,buf

	mov	ecx, DWORD PTR _buf$[esp-4]

; 8    : 		mov edx,len

	mov	edx, DWORD PTR _len$[esp-4]

; 9    : 		int	INT_VECTOR_SYS_CALL

	int	-112					; ffffff90H

; 10   : 		ret

	ret	0

; 11   : 	}
; 12   : }

	ret	0
?printx@@YAHPADH@Z ENDP					; printx
_TEXT	ENDS
END
