; Listing generated by Microsoft (R) Optimizing Compiler Version 14.00.50727.762 

	TITLE	i:\os\10\a\krnl\krnl\read.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	?read@@YAHHPADH@Z				; read
EXTRN	?send_recv@@YAHHHPAU_tagMESSAGE@@@Z:PROC	; send_recv
; Function compile flags: /Ogtpy
; File i:\os\10\a\krnl\krnl\read.cpp
;	COMDAT ?read@@YAHHPADH@Z
_TEXT	SEGMENT
_msg$ = -48						; size = 48
_fd$ = 8						; size = 4
_buf$ = 12						; size = 4
_len$ = 16						; size = 4
?read@@YAHHPADH@Z PROC					; read, COMDAT

; 6    : {

	sub	esp, 48					; 00000030H

; 7    : 	MESSAGE msg;
; 8    : 
; 9    : 	msg.FD = fd;

	mov	eax, DWORD PTR _fd$[esp+44]

; 10   : 	msg.BUF = buf;

	mov	ecx, DWORD PTR _buf$[esp+44]

; 11   : 	msg.CNT = len;

	mov	edx, DWORD PTR _len$[esp+44]
	mov	DWORD PTR _msg$[esp+56], eax

; 12   : 	msg.type = READ;
; 13   : 
; 14   : 	send_recv(BOTH,TASK_FS,&msg);

	lea	eax, DWORD PTR _msg$[esp+48]
	push	eax
	push	3
	push	3
	mov	DWORD PTR _msg$[esp+104], ecx
	mov	DWORD PTR _msg$[esp+72], edx
	mov	DWORD PTR _msg$[esp+64], 1008		; 000003f0H
	call	?send_recv@@YAHHHPAU_tagMESSAGE@@@Z	; send_recv

; 15   : 
; 16   : 	return msg.RETVAL;

	mov	eax, DWORD PTR _msg$[esp+68]

; 17   : }

	add	esp, 60					; 0000003cH
	ret	0
?read@@YAHHPADH@Z ENDP					; read
_TEXT	ENDS
END
