; Listing generated by Microsoft (R) Optimizing Compiler Version 14.00.50727.762 

	TITLE	i:\os\10\a\krnl\krnl\recv.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	?recv@@YAHHPAU_tagMESSAGE@@@Z			; recv
; Function compile flags: /Ogtpy
; File i:\os\10\a\krnl\krnl\recv.cpp
;	COMDAT ?recv@@YAHHPAU_tagMESSAGE@@@Z
_TEXT	SEGMENT
_src$ = 8						; size = 4
_p_msg$ = 12						; size = 4
?recv@@YAHHPAU_tagMESSAGE@@@Z PROC			; recv, COMDAT

; 5    : 	_asm{
; 6    : 		mov eax,SYS_RECV

	mov	eax, 1

; 7    : 		mov ecx,src

	mov	ecx, DWORD PTR _src$[esp-4]

; 8    : 		mov edx,p_msg

	mov	edx, DWORD PTR _p_msg$[esp-4]

; 9    : 		int INT_VECTOR_SYS_CALL

	int	-112					; ffffff90H

; 10   : 		ret

	ret	0

; 11   : 	}
; 12   : }

	ret	0
?recv@@YAHHPAU_tagMESSAGE@@@Z ENDP			; recv
_TEXT	ENDS
END
