; Listing generated by Microsoft (R) Optimizing Compiler Version 14.00.50727.762 

	TITLE	i:\os\10\a\krnl\krnl\send.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	?send@@YAHHPAU_tagMESSAGE@@@Z			; send
; Function compile flags: /Ogtpy
; File i:\os\10\a\krnl\krnl\send.cpp
;	COMDAT ?send@@YAHHPAU_tagMESSAGE@@@Z
_TEXT	SEGMENT
_dest$ = 8						; size = 4
_p_msg$ = 12						; size = 4
?send@@YAHHPAU_tagMESSAGE@@@Z PROC			; send, COMDAT

; 5    : 	_asm{
; 6    : 		mov eax,SYS_SEND

	mov	eax, 0

; 7    : 		mov ecx,dest

	mov	ecx, DWORD PTR _dest$[esp-4]

; 8    : 		mov edx,p_msg

	mov	edx, DWORD PTR _p_msg$[esp-4]

; 9    : 		int INT_VECTOR_SYS_CALL

	int	-112					; ffffff90H

; 10   : 		ret

	ret	0

; 11   : 	}
; 12   : }

	ret	0
?send@@YAHHPAU_tagMESSAGE@@@Z ENDP			; send
_TEXT	ENDS
END
